"""Ranking agent policy constants."""

RANKING_SOFT_RECENCY_DAYS = 28

WILDCARD_SLOT_COUNT = 2
WILDCARD_SCORE_MIN = 0.35
WILDCARD_SCORE_MAX = 0.65
WILDCARD_MIN_NOVELTY = 0.6

NOVELTY_PENALIZED_SCORE = 0.3
NOVELTY_UNSEEN_BONUS = 0.2

NEUTRAL_CATEGORY_FIT = 0.5
NEUTRAL_LOCATION_FIT = 0.5
NEUTRAL_VIBE_FIT = 0.5

FALLBACK_EXPLANATION_TEMPLATE = (
    "{title} looks worth your time this week based on your profile signals."
)
