"""Ranking agent policy constants."""

import math

from scene_scout.history_config import HARD_RECENCY_DAYS, SOFT_RECENCY_DAYS

WILDCARD_SLOT_COUNT = 2
WILDCARD_SCORE_MIN = 0.35
WILDCARD_SCORE_MAX = 0.65
WILDCARD_MIN_NOVELTY = 0.6

# Exponential novelty recency decay (days_since recommended → novelty factor).
NOVELTY_RECENCY_FLOOR = 0.5
NOVELTY_RECENCY_RECOVERY_AT_SOFT_DAYS = 0.95
_SOFT_RECENCY_WINDOW_DAYS = SOFT_RECENCY_DAYS - HARD_RECENCY_DAYS
NOVELTY_RECENCY_DECAY_LAMBDA = (
    -math.log(1.0 - NOVELTY_RECENCY_RECOVERY_AT_SOFT_DAYS) / _SOFT_RECENCY_WINDOW_DAYS
)

NOVELTY_UNSEEN_BONUS = 0.2

NEUTRAL_CATEGORY_FIT = 0.5
NEUTRAL_LOCATION_FIT = 0.5
NEUTRAL_VIBE_FIT = 0.5

FALLBACK_EXPLANATION_TEMPLATE = (
    "{title} looks worth your time this week based on your profile signals."
)
